### ISSUE TITLE
fonctionnement de ce projet

### ISSUE THREAD

**Issue by rimeh-bennjima** [domoenergytics/PythonHTML#1]
bonjour ,
je veux tourner ce projet sur mon pc mais je ne sais pas comment,

svp pourriez me dire comment je peux le tester.

merci.

**Comment by domoenergytics** [comment]
Bonjour,
Ce n'est pas un projet à proprement parlé, juste 2 bouts de code que vous pouvez réutiliser dans vos projets.
Pour les tester, faites un copier/coller et adaptatez à votre cas particulier.
finizi
